---
title: "Data Wrangling I"
author: "Molly Martorella"
date: "9/17/2019"
output: github_document
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)

```


## Load in a dataset

```{r}

##reads in a dataset

##absolute paths do not always match, use of relative paths gives path from common starting point. Always use relative path, never absolute path (this allows you to send R project folder to someone, and they can do the same analysis).

litters_data <- read_csv(file = "./data_import_examples/FAS_litters.csv")

#first step should be to print or view data.

#reform variable names in dataset if necessary:

litters_data <- janitor::clean_names(litters_data)

#use :: if did not previously load library earlier in code. Often use janitor::clean_names() because not using that library for anything else, and if attach that package can have name conflicts.

```

## Load in pups dataset:

```{r}

pups_data <- read_csv("./data_import_examples/FAS_pups.csv")

pups_data <- janitor::clean_names(pups_data)

#gives summary of variable types, histogram of values, etc.
skimr::skim(pups_data)

```


## Read in an excel file:

```{r}

mlb_data <- read_excel(path = "./data_import_examples/mlb11.xlsx")

```

## Read in SAS:

```{r}

pulse_data <- haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat")

```


