---
title: "Dplyr"
author: "Molly Martorella"
date: "9/19/2019"
output: github_document
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)

```

## Import datasets:

```{r}

litters_data <- read_csv("./data_import_examples/FAS_litters.csv")

litters_data <- janitor::clean_names(litters_data)

pups_data <- read_csv("./data_import_examples/FAS_pups.csv")

pups_data <- janitor::clean_names(pups_data)

```

## Selecting variables (columns) from the datasets:

```{r}

select(litters_data, litter_number)

select(litters_data, group, litter_number, gd0_weight)

select(litters_data, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

#gives columns back in order specified.

select(litters_data, litter_number, group, everything())

#selects litter number first, then group, and keeps everything else (just specifying order of litter_number then group before everything else).

select(litters_data, -group)

#removes the group column/variable

select(litters_data, litter_number, gd0_weight:pups_born_alive)

#keep litter number and then all columns from gd0weight to pups born alive and removes all other columns.

select(litters_data, GROUP = group, litter_number)

#select group and litter_number variables, but rename the group variable to GROUP at the same time. Can also just rename using rename function:

rename(litters_data, GROUP = group)

#renames, but does not select columns.

```

## Filter observations from the datasets:

```{r}

filter(litters_data, group == "Con7")

filter(litters_data, group == "Mod8")

filter(litters_data, gd_of_birth == 20)

filter(litters_data, gd_of_birth < 20)

filter(litters_data, gd_of_birth >= 20)

filter(litters_data, pups_born_alive < 6, group == "Con7")

#to filter multiple observations of the same variable.
filter(litters_data, group %in% c("Con7", "Mod8"))

filter(litters_data, group == "Con7" | group == "Mod8")

filter(litters_data, pups_born_alive >= 4, pups_born_alive <= 6)

filter(litters_data, gd0_weight + gd18_weight < 70)

filter(litters_data, gd0_weight < gd18_weight)

#missing values -- DON'T DO THIS:
filter(litters_data, !is.na(gd0_weight))

#DO THIS FOR NA VALUES:

drop_na(litters_data, gd0_weight)

#can specify variable to drop NAs from, or specify no variable and it will drop all NAs from all columns.

drop_na(litters_data)

```

## Mutate - edit variables inside a dataset

```{r}

mutate(litters_data, 
       wt_gain = gd18_weight - gd0_weight)

#adds new column.

mutate(litters_data, 
       wt_gain = gd18_weight - gd0_weight,
       group = tolower(group))
#now have new column and have changed group variable names to all lower case.

mutate(litters_data, 
       wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group),
       group = str_to_upper(group))

#can change the same variable within the same mutate. Executes the edits in the order you enter them in the function.

```

## Arranging - data into new order, mostly done just for viewing or double checking the data:

```{r}

arrange(litters_data, pups_born_alive)

#orders pups born alive by ascending by default.

arrange(litters_data, desc(pups_born_alive))

#specify order by descending instead.

arrange(litters_data, pups_born_alive, gd0_weight)

```

## pipe ...

```{r}

#if have situation when doing series of things on a dataframe and outputting a dataframe, can usually pipe.

litters_data <- 
  read_csv("./data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(gd0_weight)

#implicitly a pipe is saying, the result of the last thing is passed into the first argument of the next thing. Can specify though:

litters_data <- 
  read_csv("./data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names(dat = .) %>% 
  select(.dat = ., -pups_survive) %>% 
  lm(gd0_weight ~ gd18_weight, data = .)

#for lm, the first argument is not a dataframe, but can specify it later on, with a period referencing the prior pipe result.

```

```{r, eval = FALSE}

litters_data %>% view()

litters_data %>% pull(gd0_weight) %>% mean()

```





